### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by saket** [QuickBirdEng/XCoordinator#217]
Hey folks, XCoordinator looks great. Is there any possibility of adding support for macOS? Considering that you're planning to add support for watchOS, it'd be nice to cover the desktop as well!

**Comment by pauljohanneskraft** [comment]
Hello - this is a great idea - thank you for telling us. The problem with this is, that UIKit and AppKit use fundamentally different types (NSViewController vs UIViewController for example), which would require pretty much a rewrite. 
Since watchOS is very similar to iOS, the addition of that platform requires significantly less work.
Especially with macCatalyst and Apple Silicon available now, you should however already be able to use XCoordinator on Mac.
Let me know, if you would want to help with the implementation (regarding AppKit), since it would definitely be a great addition to this library.

**Comment by andrefmsilva** [comment]
I did a quick test using the sample app and it compiles for macCatalyst just fine (ofc we need to enable mac in XCoordinator Package.swift).  
The UI has some problems but i can push and pop controllers.

**Comment by andrefmsilva** [comment]
https://streamable.com/o7uwnn

**Comment by pauljohanneskraft** [comment]
The example app has (unfortunately) not even been optimized for iPad, that's why these issues are there. They should not be connected to XCoordinator directly though. 

I can't seem to be able to build the example app for Mac Catalyst though on my M1 Mac - RxCocoa seems to be unavailable on this platform for some reason - do you have an idea why that is?

**Comment by andrefmsilva** [comment]
I'll do everything again with the latest commits to find the correct steps

**Comment by andrefmsilva** [comment]
@pauljohanneskraft  News about this one?
