### ISSUE TITLE
More documentation about RedirectionRouter needed

### ISSUE THREAD

**Issue by canbalkaya** [QuickBirdEng/XCoordinator#228]
I want to use RedirectionRouter on my projects, but I just found a documentation in README about that.

**Comment by pauljohanneskraft** [comment]
Hey @canbalkaya - great, which questions are still open? There is both documentation about it in the README as well as code documentation.

**Comment by canbalkaya** [comment]
Hi.

I want to know if RedirectionRouter can help me to segment a huge flow.

For example, I have "a huge flow" within some "small flows"; permission, authentication and onboarding. These are all linked with just one UINavigationController. I use coordinators for each UIViewController because of my project's modularity and complexity. Therefore I always add another child to push another UIViewController.

Maybe RedirectionRouter can help to bind all these "small flows" each other. So I don't need to use the same push actions more than once in different coordinators: I check multiple times on different coordinators whether the user is authenticated and which onboarding pages has completed.

I hope I able to explain my problem to you.

**Comment by pauljohanneskraft** [comment]
Okay, there are different options to do this:

### Option 1: Multiple coordinators with the same rootViewController.

Whenever you are creating a navigator, you can specify a `rootViewController` in its initializer that the coordinator is performing transitions on. For NavigationCoodinators, you will probably need to use the `.set` transition more often than `.push` to actually also replace the first child of the UINavigationController, but you will get the hang of it.

### Option 2: RedirectionRouter

You can use a RedirectionRouter to map child routes to parent equivalents.

```swift
enum Child1Route: Route {
    case someRoute
}

enum ParentRoute: Route {
    case anotherRoute
}
```

Okay, so we have these two routes - `ChildRoute` is used by the RedirectionRouter and `ParentRoute` is used by the parent coordinator. This means that in the end, the parent coordinator is deciding all of the transitions - I'm guessing that you do not actually want this here, since otherwise you have rather big dependencies between these separate flows, but if you have the same ParentRoute that needs to be executed from multiple children, this might make sense.

I'm not entirely sure what issue you are trying to solve exactly, so a small example project would be highly appreciated.

**Comment by pauljohanneskraft** [comment]
Closed due to inactivity
